### ISSUE TITLE
panic: asset: Asset(fix-strings.md): Asset fix-strings.md not found

### ISSUE THREAD

**Issue by bitfield** [tehsphinx/exalysis#52]
On 0dabe67ee383a5f838e339d005fd665eb822f691:

```
go generate ./...
go: finding github.com/tehsphinx/astrav v0.0.0-20181205091422-e6b176146820
go: downloading github.com/tehsphinx/astrav v0.0.0-20181205091422-e6b176146820

go build -o ./exalysis ./cmd/exalysis

./exalysis -watch
panic: asset: Asset(fix-strings.md): Asset fix-strings.md not found

goroutine 1 [running]:
github.com/tehsphinx/exalysis/track/raindrops/tpl.MustAsset(0x135fc1f, 0xe, 0x95, 0x0, 0x0)
        /Users/john/git/bitfield/exalysis/track/raindrops/tpl/bindata.go:307 +0x12e
github.com/tehsphinx/exalysis/gtpl.NewStringTemplate(0x135fc1f, 0xe, 0x136dc78, 0x135f215, 0xc, 0xc00030efa0, 0x95)
        /Users/john/git/bitfield/exalysis/gtpl/template.go:15 +0x3e
```

**Comment by tehsphinx** [comment]
Fixed with #53

Sorry about that.
