### ISSUE TITLE
hamming: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by bitfield** [tehsphinx/exalysis#70]
[Solution dedb76a99f5f4b80a2e3b170234fb06b](https://exercism.io/mentor/solutions/dedb76a99f5f4b80a2e3b170234fb06b):

```go
package hamming

import (
	"errors"
)

func Distance(a, b string) (distance int, err error) {
	r1 := []rune(a)
	r2 := []rune(b)

	if len(r1) != len(r2) {
		err = errors.New("Different size of strings.")
		return
	}

	for i, v := range r1 {
		if r2[i] != v {
			distance++
		}
	}
	return
}
```

Output:

```
I know the "hamming" exercise, so I'll try to make some specific suggestions about it, as well as the general code checks:
golint:          FAIL
comments: exported function Distance should have comment or be unexported
        hamming.go:7:1
        doc: https://golang.org/wiki/CodeReviewComments#doc-comments
errors: error strings should not be capitalized or end with punctuation or a newline
        hamming.go:12:20
        doc: https://golang.org/wiki/CodeReviewComments#error-strings

gofmt:           OK
go test:         OK
go test -race:   SKIPPED
go vet:          OK
golangci-lint:   OK
benchmarks:      SKIPPED
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tehsphinx/exalysis/track/hamming.examReturnZeroValue(0xc0000be8c0, 0xc000254000)
        /Users/john/git/bitfield/exalysis/track/hamming/hamming.go:35 +0x341
github.com/tehsphinx/exalysis/track/hamming.Suggest(0xc0000be8c0, 0xc000254000)
        /Users/john/git/bitfield/exalysis/track/hamming/hamming.go:17 +0x7a
github.com/tehsphinx/exalysis.GetSuggestions(0x1369634, 0x1, 0x2a, 0xc00044425d, 0xc0000bbf48, 0x10cabce)
        /Users/john/git/bitfield/exalysis/suggestion.go:66 +0x53b
main.main()
        /Users/john/git/bitfield/exalysis/cmd/exalysis/main.go:35 +0x80
```

**Comment by bitfield** [comment]
https://exercism.io/mentor/solutions/06a0cabc05a542649b15e84c0eead8e1
